"use client";

import { useLocale } from "next-intl";

const content = {
  es: { eyebrow: "NUESTRA BASE", title: "Misión, Pasión y Visión", values: [{ title: "Misión", icon: "target", description: "Contribuir al desarrollo de nuestros clientes, partners, colaboradores y aliados estratégicos mediante la mejora continua de las personas y la construcción de negocios sostenibles, sustentados en la confianza, el valor compartido y relaciones de largo plazo." }, { title: "Pasión", icon: "favorite", description: "Nos mueve la convicción de hacer las cosas bien, incluso cuando nadie está viendo. Creemos en la lealtad, en la palabra cumplida y en la confianza que se construye con hechos." }, { title: "Visión", icon: "visibility", description: "Consolidarnos como un grupo empresarial global referente por su capacidad de construir, integrar y escalar ecosistemas de negocio, generando crecimiento sostenible e innovación constante." }] },
  en: { eyebrow: "OUR FOUNDATION", title: "Mission, Passion and Vision", values: [{ title: "Mission", icon: "target", description: "To contribute to the development of our clients, partners, collaborators, and strategic allies through continuous personal growth and sustainable businesses built on trust, shared value, and long-term relationships." }, { title: "Passion", icon: "favorite", description: "We are driven by the conviction to do things well, even when no one is watching. We believe in loyalty, promises kept, and trust built through action." }, { title: "Vision", icon: "visibility", description: "To become a benchmark global business group through our capacity to build, integrate, and scale business ecosystems, creating sustainable growth and continual innovation." }] },
};

export function ValuesSection() {
  const locale = useLocale(); const t = content[locale === "en" ? "en" : "es"];
  return <section id="mission" className="mx-auto max-w-7xl px-6 py-20 sm:px-8 sm:py-24 md:py-32"><div className="mb-12 sm:mb-16"><p className="editorial-label mb-2 text-gray">{t.eyebrow}</p><h2 className="font-serif text-4xl font-black leading-[1.1] tracking-tight text-black sm:text-5xl md:text-6xl">{t.title}</h2></div><div className="grid grid-cols-1 gap-5 sm:gap-6 md:grid-cols-3">{t.values.map((value) => <article key={value.title} className="group rounded-2xl border border-light-gray bg-white p-6 transition-all hover:-translate-y-1 hover:border-dark-gray hover:shadow-[0_14px_32px_rgba(37,37,37,0.08)] sm:p-8"><div className="mb-7 flex h-14 w-14 items-center justify-center rounded-full border border-light-gray bg-light-gray/10 transition-colors group-hover:bg-black"><span className="material-symbols-outlined text-xl text-dark-gray transition-colors group-hover:text-white">{value.icon}</span></div><h3 className="mb-4 font-serif text-2xl font-semibold tracking-tight text-black sm:text-3xl">{value.title}</h3><p className="text-base font-light leading-[1.8] text-dark-gray sm:text-lg">{value.description}</p></article>)}</div></section>;
}
